version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17.0

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}
      - run: npm run build

workflows:
  build-deploy:
    jobs:
      - build
